[package]
name = "esploro"
version = "0.4.2"
description = "A modern, sleek and fast database client for PostgreSQL, MySQL, and MariaDB."
authors = ["Matija Munjaković"]
edition = "2021"
license = "MIT"

[lib]
name = "esploro_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "0.7", features = ["with-serde_json-1"] }
deadpool-postgres = { version = "0.12", features = ["rt_tokio_1"] }
mysql_async = { version = "0.34", features = [] }
keyring = "2"
chrono = { version = "0.4", features = ["serde"] }
tauri-plugin-updater = "2"
