// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	queryTableData: (sessionId: string, request: TableQueryRequest) => __TAURI_INVOKE<TableQueryResult>("query_table_data", { sessionId, request }),
	queryTableCount: (sessionId: string, request: TableQueryRequest) => __TAURI_INVOKE<TableCountResult>("query_table_count", { sessionId, request }),
	updateRows: (sessionId: string, request: UpdateRowsRequest) => __TAURI_INVOKE<null>("update_rows", { sessionId, request }),
	previewUpdateRowsSql: (sessionId: string, request: UpdateRowsRequest) => __TAURI_INVOKE<string>("preview_update_rows_sql", { sessionId, request }),
	deleteRows: (sessionId: string, request: DeleteRowsRequest) => __TAURI_INVOKE<DeleteRowResult[]>("delete_rows", { sessionId, request }),
	previewDeleteRowsSql: (sessionId: string, request: DeleteRowsRequest) => __TAURI_INVOKE<string>("preview_delete_rows_sql", { sessionId, request }),
	executeSql: (sessionId: string, sql: string) => __TAURI_INVOKE<QueryResult[]>("execute_sql", { sessionId, sql }),
	saveQuery: (id: string | null, name: string, folder: string | null, sql: string) => __TAURI_INVOKE<string>("save_query", { id, name, folder, sql }),
	listSavedQueries: () => __TAURI_INVOKE<SavedQuery[]>("list_saved_queries"),
	getSavedQuery: (id: string) => __TAURI_INVOKE<SavedQuery>("get_saved_query", { id }),
	deleteSavedQuery: (id: string) => __TAURI_INVOKE<null>("delete_saved_query", { id }),
};

/* Types */
export type AppError = {
	kind: string,
	message: string,
	code: string | null,
	position: number | null,
};

export type AppErrorWire = {
	kind: string,
	message: string,
	code: string | null,
	position: number | null,
};

export type CellValue = { t: "null" } | { t: "bool"; v: boolean } | { t: "int"; v: number } | { t: "float"; v: number | null } | { t: "text"; v: string } | { t: "json"; v: JsonValue } | { t: "other"; v: string };

export type ColumnChange = {
	column: string,
	value: string | null,
};

export type ColumnFilter = {
	column: string,
	operator: FilterOperator,
	value: string | null,
};

export type DeleteRowRequest = {
	pkConditions: PkCondition[],
	ctid: string | null,
};

export type DeleteRowResult = {
	sql: string,
	error: string | null,
};

export type DeleteRowsRequest = {
	schema: string,
	table: string,
	rows: DeleteRowRequest[],
};

export type FilterOperator = "Eq" | "Neq" | "Like" | "ILike" | "Gt" | "Lt" | "Gte" | "Lte" | "IsNull" | "IsNotNull";

export type JsonValue = "Null" | boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue };

export type PkCondition = {
	column: string,
	value: string,
};

export type QueryError = {
	message: string,
	position: number | null,
	code: string | null,
};

export type QueryResult = {
	columns: ResultColumn[],
	rows: CellValue[][],
	rowsAffected: number | null,
	executionMs: number,
	error: QueryError | null,
};

export type ResultColumn = {
	name: string,
	dataType: string,
	isNullable: boolean,
	isPrimaryKey: boolean,
	isForeignKey: boolean,
	isEnum: boolean,
};

export type RowChange = {
	pkConditions: PkCondition[],
	ctid: string | null,
	columnChanges: ColumnChange[],
};

export type SavedQuery = {
	id: string,
	name: string,
	folder: string | null,
	sql: string,
	createdAt: string,
	updatedAt: string,
};

export type SortDirection = "Asc" | "Desc";

export type TableCountResult = {
	count: number,
	isEstimate: boolean,
};

export type TableQueryRequest = {
	database: string,
	schema: string,
	table: string,
	filters: ColumnFilter[],
	sortColumn: string | null,
	sortDirection: SortDirection | null,
	page: number,
	pageSize: number,
	rawWhere?: string | null,
};

export type TableQueryResult = {
	columns: ResultColumn[],
	rows: CellValue[][],
	ctids: (string | null)[],
	page: number,
	pageSize: number,
	executionMs: number,
};

export type UpdateRowsRequest = {
	schema: string,
	table: string,
	changes: RowChange[],
};

