// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listConnections: () => __TAURI_INVOKE<ConnectionProfile[]>("list_connections"),
	createConnection: (input: ConnectionInput, password: string) => __TAURI_INVOKE<string>("create_connection", { input, password }),
	updateConnection: (id: string, input: ConnectionInput, password: string | null) => __TAURI_INVOKE<null>("update_connection", { id, input, password }),
	deleteConnection: (id: string) => __TAURI_INVOKE<null>("delete_connection", { id }),
	testConnection: (input: ConnectionInput, password: string) => __TAURI_INVOKE<number>("test_connection", { input, password }),
	connect: (id: string) => __TAURI_INVOKE<string>("connect", { id }),
	disconnect: (sessionId: string) => __TAURI_INVOKE<null>("disconnect", { sessionId }),
	queryTableData: (sessionId: string, request: TableQueryRequest) => __TAURI_INVOKE<TableQueryResult>("query_table_data", { sessionId, request }),
	queryTableCount: (sessionId: string, request: TableQueryRequest) => __TAURI_INVOKE<TableCountResult>("query_table_count", { sessionId, request }),
	updateRows: (sessionId: string, request: UpdateRowsRequest) => __TAURI_INVOKE<null>("update_rows", { sessionId, request }),
	previewUpdateRowsSql: (sessionId: string, request: UpdateRowsRequest) => __TAURI_INVOKE<string>("preview_update_rows_sql", { sessionId, request }),
	deleteRows: (sessionId: string, request: DeleteRowsRequest) => __TAURI_INVOKE<DeleteRowResult[]>("delete_rows", { sessionId, request }),
	previewDeleteRowsSql: (sessionId: string, request: DeleteRowsRequest) => __TAURI_INVOKE<string>("preview_delete_rows_sql", { sessionId, request }),
	executeSql: (sessionId: string, sql: string) => __TAURI_INVOKE<QueryResult[]>("execute_sql", { sessionId, sql }),
	saveQuery: (id: string | null, name: string, folder: string | null, sql: string) => __TAURI_INVOKE<string>("save_query", { id, name, folder, sql }),
	listSavedQueries: () => __TAURI_INVOKE<SavedQuery[]>("list_saved_queries"),
	getSavedQuery: (id: string) => __TAURI_INVOKE<SavedQuery>("get_saved_query", { id }),
	deleteSavedQuery: (id: string) => __TAURI_INVOKE<null>("delete_saved_query", { id }),
	listSchemas: (sessionId: string, database: string) => __TAURI_INVOKE<string[]>("list_schemas", { sessionId, database }),
	listObjects: (sessionId: string, database: string, schema: string) => __TAURI_INVOKE<SchemaObjects>("list_objects", { sessionId, database, schema }),
	listColumns: (sessionId: string, database: string, schema: string, table: string) => __TAURI_INVOKE<ColumnDef[]>("list_columns", { sessionId, database, schema, table }),
	listRoles: (sessionId: string) => __TAURI_INVOKE<RoleSummary[]>("list_roles", { sessionId }),
	listRoleMembers: (sessionId: string, roleName: string) => __TAURI_INVOKE<RoleMembers>("list_role_members", { sessionId, roleName }),
	getRoleDependents: (sessionId: string, roleName: string) => __TAURI_INVOKE<RoleDependent[]>("get_role_dependents", { sessionId, roleName }),
	createRole: (sessionId: string, request: CreateRoleRequest) => __TAURI_INVOKE<null>("create_role", { sessionId, request }),
	alterRole: (sessionId: string, roleName: string, request: AlterRoleRequest) => __TAURI_INVOKE<null>("alter_role", { sessionId, roleName, request }),
	dropRole: (sessionId: string, roleName: string) => __TAURI_INVOKE<null>("drop_role", { sessionId, roleName }),
	manageRoleMembership: (sessionId: string, ops: MembershipOp[]) => __TAURI_INVOKE<MembershipResult[]>("manage_role_membership", { sessionId, ops }),
	listRolePrivileges: (sessionId: string, roleName: string) => __TAURI_INVOKE<RolePrivileges>("list_role_privileges", { sessionId, roleName }),
	manageRolePrivileges: (sessionId: string, roleName: string, ops: PrivilegeOp[]) => __TAURI_INVOKE<PrivilegeResult[]>("manage_role_privileges", { sessionId, roleName, ops }),
	listTablePrivileges: (sessionId: string, schema: string, table: string) => __TAURI_INVOKE<TableGrantee[]>("list_table_privileges", { sessionId, schema, table }),
	manageTablePrivileges: (sessionId: string, schema: string, table: string, ops: TablePrivilegeOp[]) => __TAURI_INVOKE<PrivilegeResult[]>("manage_table_privileges", { sessionId, schema, table, ops }),
	listSchemaPrivileges: (sessionId: string, schema: string) => __TAURI_INVOKE<SchemaInfo>("list_schema_privileges", { sessionId, schema }),
	manageSchemaPrivileges: (sessionId: string, schema: string, ops: SchemaPrivilegeOp[]) => __TAURI_INVOKE<PrivilegeResult[]>("manage_schema_privileges", { sessionId, schema, ops }),
};

/* Types */
export type AlterRoleRequest = {
	isSuperuser?: boolean | null,
	inherit?: boolean | null,
	createRole?: boolean | null,
	createDb?: boolean | null,
	canLogin?: boolean | null,
	replication?: boolean | null,
	bypassRls?: boolean | null,
	connLimit?: number | null,
	/**  ISO date string to set, empty string to clear (sets to 'infinity') */
	validUntil?: string | null,
	/**  Set-only. None = don't change. Some("") = set to NULL. Some(pw) = set new password. */
	password?: string | null,
};

export type AppError = {
	kind: string,
	message: string,
	code: string | null,
	position: number | null,
};

export type AppErrorWire = {
	kind: string,
	message: string,
	code: string | null,
	position: number | null,
};

export type CellValue = { t: "null" } | { t: "bool"; v: boolean } | { t: "int"; v: number } | { t: "float"; v: number | null } | { t: "text"; v: string } | { t: "json"; v: JsonValue } | { t: "other"; v: string };

export type ColumnChange = {
	column: string,
	value: string | null,
};

export type ColumnDef = {
	name: string,
	dataType: string,
	isNullable: boolean,
	columnDefault: string | null,
	isPrimaryKey: boolean,
	isForeignKey: boolean,
	foreignKeyRef: string | null,
	isEnum: boolean,
};

export type ColumnFilter = {
	column: string,
	operator: FilterOperator,
	value: string | null,
};

/**  What the frontend sends for create/update/test (no timestamps, no id) */
export type ConnectionInput = {
	displayName: string,
	color: string | null,
	folder: string | null,
	driver?: DbDriver,
	host: string | null,
	port: number,
	socketPath: string | null,
	database: string,
	username: string,
	sslMode: SslMode,
	poolMaxConnections?: number,
};

export type ConnectionProfile = {
	id: string,
	displayName: string,
	color: string | null,
	folder: string | null,
	driver?: DbDriver,
	/**  TCP hostname/IP; None when using socket_path */
	host: string | null,
	port: number,
	/**  Unix socket directory path (e.g. /var/run/postgresql) */
	socketPath: string | null,
	database: string,
	username: string,
	sslMode: SslMode,
	poolMaxConnections?: number,
	createdAt: string,
	updatedAt: string,
};

export type CreateRoleRequest = {
	name: string,
	isSuperuser?: boolean | null,
	inherit?: boolean | null,
	createRole?: boolean | null,
	createDb?: boolean | null,
	canLogin?: boolean | null,
	replication?: boolean | null,
	bypassRls?: boolean | null,
	connLimit?: number | null,
	validUntil?: string | null,
	password?: string | null,
};

export type DbDriver = "postgres" | "mysql";

export type DeleteRowRequest = {
	pkConditions: PkCondition[],
	ctid: string | null,
};

export type DeleteRowResult = {
	sql: string,
	error: string | null,
};

export type DeleteRowsRequest = {
	schema: string,
	table: string,
	rows: DeleteRowRequest[],
};

export type FilterOperator = "Eq" | "Neq" | "Like" | "ILike" | "Gt" | "Lt" | "Gte" | "Lte" | "IsNull" | "IsNotNull";

export type FunctionSummary = {
	name: string,
	resultType: string,
};

export type JsonValue = "Null" | boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue };

export type MembershipOp = {
	op: string,
	role: string,
	member: string,
};

export type MembershipResult = {
	op: string,
	role: string,
	member: string,
	error: string | null,
};

export type PkCondition = {
	column: string,
	value: string,
};

export type PrivilegeOp = {
	op: string,
	objectType: string,
	schema: string,
	name: string,
	privilege: string,
};

export type PrivilegeResult = {
	sql: string,
	error: string | null,
};

export type QueryError = {
	message: string,
	position: number | null,
	code: string | null,
};

export type QueryResult = {
	columns: ResultColumn[],
	rows: CellValue[][],
	rowsAffected: number | null,
	executionMs: number,
	error: QueryError | null,
};

export type ResultColumn = {
	name: string,
	dataType: string,
	isNullable: boolean,
	isPrimaryKey: boolean,
	isForeignKey: boolean,
	isEnum: boolean,
};

export type RoleDependent = {
	kind: string,
	name: string,
};

export type RoleMembers = {
	memberOf: string[],
	members: string[],
};

export type RolePrivileges = {
	tableGrants: RoleTableGrant[],
	schemaGrants: RoleSchemaGrant[],
};

export type RoleSchemaGrant = {
	schema: string,
	privileges: string[],
};

export type RoleSummary = {
	name: string,
	isSuperuser: boolean,
	inherit: boolean,
	createRole: boolean,
	createDb: boolean,
	canLogin: boolean,
	replication: boolean,
	bypassRls: boolean,
	connLimit: number,
	validUntil: string | null,
};

export type RoleTableGrant = {
	schema: string,
	table: string,
	privileges: string[],
};

export type RowChange = {
	pkConditions: PkCondition[],
	ctid: string | null,
	columnChanges: ColumnChange[],
};

export type SavedQuery = {
	id: string,
	name: string,
	folder: string | null,
	sql: string,
	createdAt: string,
	updatedAt: string,
};

export type SchemaGrantee = {
	grantee: string,
	privileges: string[],
};

export type SchemaInfo = {
	owner: string,
	grantees: SchemaGrantee[],
};

export type SchemaObjects = {
	tables: TableSummary[],
	views: string[],
	sequences: string[],
	functions: FunctionSummary[],
};

export type SchemaPrivilegeOp = {
	op: string,
	grantee: string,
	privilege: string,
};

export type SortDirection = "Asc" | "Desc";

export type SslMode = "disable" | "prefer" | "require" | "verifyFull";

export type TableCountResult = {
	count: number,
	isEstimate: boolean,
};

export type TableGrantee = {
	grantee: string,
	privileges: string[],
};

export type TablePrivilegeOp = {
	op: string,
	grantee: string,
	privilege: string,
};

export type TableQueryRequest = {
	database: string,
	schema: string,
	table: string,
	filters: ColumnFilter[],
	sortColumn: string | null,
	sortDirection: SortDirection | null,
	page: number,
	pageSize: number,
	rawWhere?: string | null,
};

export type TableQueryResult = {
	columns: ResultColumn[],
	rows: CellValue[][],
	ctids: (string | null)[],
	page: number,
	pageSize: number,
	executionMs: number,
};

export type TableSummary = {
	name: string,
	estimatedRowCount: number | null,
};

export type UpdateRowsRequest = {
	schema: string,
	table: string,
	changes: RowChange[],
};

