// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listConnections: () => __TAURI_INVOKE<ConnectionProfile[]>("list_connections"),
	createConnection: (input: ConnectionInput, password: string) => __TAURI_INVOKE<string>("create_connection", { input, password }),
	updateConnection: (id: string, input: ConnectionInput, password: string | null) => __TAURI_INVOKE<null>("update_connection", { id, input, password }),
	deleteConnection: (id: string) => __TAURI_INVOKE<null>("delete_connection", { id }),
	testConnection: (input: ConnectionInput, password: string) => __TAURI_INVOKE<number>("test_connection", { input, password }),
	connect: (id: string) => __TAURI_INVOKE<string>("connect", { id }),
	disconnect: (sessionId: string) => __TAURI_INVOKE<null>("disconnect", { sessionId }),
	queryTableData: (sessionId: string, request: TableQueryRequest) => __TAURI_INVOKE<TableQueryResult>("query_table_data", { sessionId, request }),
	queryTableCount: (sessionId: string, request: TableQueryRequest) => __TAURI_INVOKE<TableCountResult>("query_table_count", { sessionId, request }),
	updateRows: (sessionId: string, request: UpdateRowsRequest) => __TAURI_INVOKE<null>("update_rows", { sessionId, request }),
	previewUpdateRowsSql: (sessionId: string, request: UpdateRowsRequest) => __TAURI_INVOKE<string>("preview_update_rows_sql", { sessionId, request }),
	deleteRows: (sessionId: string, request: DeleteRowsRequest) => __TAURI_INVOKE<DeleteRowResult[]>("delete_rows", { sessionId, request }),
	previewDeleteRowsSql: (sessionId: string, request: DeleteRowsRequest) => __TAURI_INVOKE<string>("preview_delete_rows_sql", { sessionId, request }),
	executeSql: (sessionId: string, sql: string) => __TAURI_INVOKE<QueryResult[]>("execute_sql", { sessionId, sql }),
	saveQuery: (id: string | null, name: string, folder: string | null, sql: string) => __TAURI_INVOKE<string>("save_query", { id, name, folder, sql }),
	listSavedQueries: () => __TAURI_INVOKE<SavedQuery[]>("list_saved_queries"),
	getSavedQuery: (id: string) => __TAURI_INVOKE<SavedQuery>("get_saved_query", { id }),
	deleteSavedQuery: (id: string) => __TAURI_INVOKE<null>("delete_saved_query", { id }),
	listSchemas: (sessionId: string, database: string) => __TAURI_INVOKE<string[]>("list_schemas", { sessionId, database }),
	listObjects: (sessionId: string, database: string, schema: string) => __TAURI_INVOKE<SchemaObjects>("list_objects", { sessionId, database, schema }),
	listColumns: (sessionId: string, database: string, schema: string, table: string) => __TAURI_INVOKE<ColumnDef[]>("list_columns", { sessionId, database, schema, table }),
};

/* Types */
export type AppError = {
	kind: string,
	message: string,
	code: string | null,
	position: number | null,
};

export type AppErrorWire = {
	kind: string,
	message: string,
	code: string | null,
	position: number | null,
};

export type CellValue = { t: "null" } | { t: "bool"; v: boolean } | { t: "int"; v: number } | { t: "float"; v: number | null } | { t: "text"; v: string } | { t: "json"; v: JsonValue } | { t: "other"; v: string };

export type ColumnChange = {
	column: string,
	value: string | null,
};

export type ColumnDef = {
	name: string,
	dataType: string,
	isNullable: boolean,
	columnDefault: string | null,
	isPrimaryKey: boolean,
	isForeignKey: boolean,
	foreignKeyRef: string | null,
	isEnum: boolean,
};

export type ColumnFilter = {
	column: string,
	operator: FilterOperator,
	value: string | null,
};

/**  What the frontend sends for create/update/test (no timestamps, no id) */
export type ConnectionInput = {
	displayName: string,
	color: string | null,
	folder: string | null,
	driver?: DbDriver,
	host: string | null,
	port: number,
	socketPath: string | null,
	database: string,
	username: string,
	sslMode: SslMode,
	poolMaxConnections?: number,
};

export type ConnectionProfile = {
	id: string,
	displayName: string,
	color: string | null,
	folder: string | null,
	driver?: DbDriver,
	/**  TCP hostname/IP; None when using socket_path */
	host: string | null,
	port: number,
	/**  Unix socket directory path (e.g. /var/run/postgresql) */
	socketPath: string | null,
	database: string,
	username: string,
	sslMode: SslMode,
	poolMaxConnections?: number,
	createdAt: string,
	updatedAt: string,
};

export type DbDriver = "postgres" | "mysql";

export type DeleteRowRequest = {
	pkConditions: PkCondition[],
	ctid: string | null,
};

export type DeleteRowResult = {
	sql: string,
	error: string | null,
};

export type DeleteRowsRequest = {
	schema: string,
	table: string,
	rows: DeleteRowRequest[],
};

export type FilterOperator = "Eq" | "Neq" | "Like" | "ILike" | "Gt" | "Lt" | "Gte" | "Lte" | "IsNull" | "IsNotNull";

export type FunctionSummary = {
	name: string,
	resultType: string,
};

export type JsonValue = "Null" | boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue };

export type PkCondition = {
	column: string,
	value: string,
};

export type QueryError = {
	message: string,
	position: number | null,
	code: string | null,
};

export type QueryResult = {
	columns: ResultColumn[],
	rows: CellValue[][],
	rowsAffected: number | null,
	executionMs: number,
	error: QueryError | null,
};

export type ResultColumn = {
	name: string,
	dataType: string,
	isNullable: boolean,
	isPrimaryKey: boolean,
	isForeignKey: boolean,
	isEnum: boolean,
};

export type RowChange = {
	pkConditions: PkCondition[],
	ctid: string | null,
	columnChanges: ColumnChange[],
};

export type SavedQuery = {
	id: string,
	name: string,
	folder: string | null,
	sql: string,
	createdAt: string,
	updatedAt: string,
};

export type SchemaObjects = {
	tables: TableSummary[],
	views: string[],
	sequences: string[],
	functions: FunctionSummary[],
};

export type SortDirection = "Asc" | "Desc";

export type SslMode = "disable" | "prefer" | "require" | "verifyFull";

export type TableCountResult = {
	count: number,
	isEstimate: boolean,
};

export type TableQueryRequest = {
	database: string,
	schema: string,
	table: string,
	filters: ColumnFilter[],
	sortColumn: string | null,
	sortDirection: SortDirection | null,
	page: number,
	pageSize: number,
	rawWhere?: string | null,
};

export type TableQueryResult = {
	columns: ResultColumn[],
	rows: CellValue[][],
	ctids: (string | null)[],
	page: number,
	pageSize: number,
	executionMs: number,
};

export type TableSummary = {
	name: string,
	estimatedRowCount: number | null,
};

export type UpdateRowsRequest = {
	schema: string,
	table: string,
	changes: RowChange[],
};

