use std::collections::HashMap;

use mysql_async::Value;

use super::type_mapping::json_to_pg_array_literal;
use super::{validate_column_identifier, DeleteRowRequest, RowChange};

pub(super) struct PgMutationSql {
    pub sql: String,
    pub params: Vec<String>,
}

pub(super) struct PgDeleteSql {
    pub exec_sql: String,
    pub display_sql: String,
    pub params: Vec<String>,
}

pub(super) struct MysqlMutationSql {
    pub sql: String,
    pub params: Vec<Value>,
}

pub(super) struct MysqlDeleteSql {
    pub exec_sql: String,
    pub display_sql: String,
    pub params: Vec<Value>,
}

pub(super) fn sql_escape_string(s: &str) -> String {
    s.replace('\'', "''")
}

pub(super) fn build_pg_update_sql(
    schema: &str,
    table: &str,
    change: &RowChange,
    col_type_map: &HashMap<String, String>,
    col_cast_map: &HashMap<String, String>,
) -> Result<PgMutationSql, String> {
    for cc in &change.column_changes {
        validate_column_identifier(&cc.column)?;
    }
    for pk in &change.pk_conditions {
        validate_column_identifier(&pk.column)?;
    }

    let mut params: Vec<String> = vec![];
    let mut set_parts: Vec<String> = vec![];

    for cc in &change.column_changes {
        if let Some(ref val) = cc.value {
            let udt = col_type_map
                .get(&cc.column)
                .map(|s| s.as_str())
                .unwrap_or("text");
            if udt.starts_with('_') {
                let elem_type = udt.trim_start_matches('_');
                params.push(json_to_pg_array_literal(val)?);
                let p = params.len();
                set_parts.push(format!("\"{}\" = ${}::text::{}[]", cc.column, p, elem_type));
            } else {
                params.push(val.clone());
                let p = params.len();
                let cast = col_cast_map
                    .get(&cc.column)
                    .map(|s| s.as_str())
                    .unwrap_or("text");
                set_parts.push(format!("\"{}\" = ${}::text::{}", cc.column, p, cast));
            }
        } else {
            set_parts.push(format!("\"{}\" = NULL", cc.column));
        }
    }

    let where_clause = build_pg_exec_where(change, col_cast_map, &mut params)
        .map_err(|_| "Row change has no PK conditions and no ctid".to_string())?;

    Ok(PgMutationSql {
        sql: format!(
            "UPDATE \"{schema}\".\"{table}\" SET {} WHERE {where_clause}",
            set_parts.join(", ")
        ),
        params,
    })
}

pub(super) fn build_pg_update_preview_sql(
    schema: &str,
    table: &str,
    changes: &[RowChange],
    col_type_map: &HashMap<String, String>,
    col_cast_map: &HashMap<String, String>,
) -> Result<String, String> {
    let mut statements: Vec<String> = vec![];

    for change in changes {
        if change.column_changes.is_empty() {
            continue;
        }
        statements.push(build_pg_update_preview_statement(
            schema,
            table,
            change,
            col_type_map,
            col_cast_map,
        )?);
    }

    if statements.is_empty() {
        return Ok(String::new());
    }

    Ok(format!(
        "BEGIN;\n-- Generated by Esploro from inline edits. Review before running.\n{}\nCOMMIT;",
        statements.join("\n"),
    ))
}

fn build_pg_update_preview_statement(
    schema: &str,
    table: &str,
    change: &RowChange,
    col_type_map: &HashMap<String, String>,
    col_cast_map: &HashMap<String, String>,
) -> Result<String, String> {
    for cc in &change.column_changes {
        validate_column_identifier(&cc.column)?;
    }
    for pk in &change.pk_conditions {
        validate_column_identifier(&pk.column)?;
    }

    let mut set_parts: Vec<String> = vec![];
    for cc in &change.column_changes {
        let part = match &cc.value {
            None => format!("\"{}\" = NULL", cc.column),
            Some(val) => {
                let udt = col_type_map
                    .get(&cc.column)
                    .map(|s| s.as_str())
                    .unwrap_or("text");
                if udt.starts_with('_') {
                    let elem_type = udt.trim_start_matches('_');
                    let pg_array = json_to_pg_array_literal(val)?;
                    format!(
                        "\"{}\" = '{}'::{}[]",
                        cc.column,
                        sql_escape_string(&pg_array),
                        elem_type
                    )
                } else {
                    let cast = col_cast_map
                        .get(&cc.column)
                        .map(|s| s.as_str())
                        .unwrap_or("text");
                    let escaped = sql_escape_string(val);
                    if cast == "text" {
                        format!("\"{}\" = '{}'", cc.column, escaped)
                    } else {
                        format!("\"{}\" = '{}'::{}", cc.column, escaped, cast)
                    }
                }
            }
        };
        set_parts.push(part);
    }

    let where_clause = build_pg_inline_where_from_change(change, col_cast_map)
        .map_err(|_| "Row change has no PK conditions and no ctid".to_string())?;

    Ok(format!(
        "UPDATE \"{schema}\".\"{table}\" SET {} WHERE {where_clause};",
        set_parts.join(", ")
    ))
}

pub(super) fn build_mysql_update_sql(
    schema: &str,
    table: &str,
    change: &RowChange,
) -> Result<MysqlMutationSql, String> {
    for cc in &change.column_changes {
        validate_column_identifier(&cc.column)?;
    }
    for pk in &change.pk_conditions {
        validate_column_identifier(&pk.column)?;
    }
    if change.pk_conditions.is_empty() {
        return Err("MySQL row change has no PK conditions".to_string());
    }

    let mut set_params: Vec<Value> = vec![];
    let mut set_parts: Vec<String> = vec![];

    for cc in &change.column_changes {
        if let Some(ref val) = cc.value {
            set_parts.push(format!("`{}` = ?", cc.column));
            set_params.push(Value::Bytes(val.as_bytes().to_vec()));
        } else {
            set_parts.push(format!("`{}` = NULL", cc.column));
        }
    }

    let mut where_parts: Vec<String> = vec![];
    let mut where_params: Vec<Value> = vec![];
    for pk in &change.pk_conditions {
        where_parts.push(format!("`{}` = ?", pk.column));
        where_params.push(Value::Bytes(pk.value.as_bytes().to_vec()));
    }

    Ok(MysqlMutationSql {
        sql: format!(
            "UPDATE `{schema}`.`{table}` SET {} WHERE {}",
            set_parts.join(", "),
            where_parts.join(" AND "),
        ),
        params: set_params.into_iter().chain(where_params).collect(),
    })
}

pub(super) fn build_mysql_update_preview_sql(
    schema: &str,
    table: &str,
    changes: &[RowChange],
) -> Result<String, String> {
    let mut statements: Vec<String> = vec![];

    for change in changes {
        if change.column_changes.is_empty() {
            continue;
        }
        statements.push(build_mysql_update_preview_statement(schema, table, change)?);
    }

    if statements.is_empty() {
        return Ok(String::new());
    }

    Ok(format!(
        "START TRANSACTION;\n-- Generated by Esploro from inline edits. Review before running.\n{}\nCOMMIT;",
        statements.join("\n"),
    ))
}

fn build_mysql_update_preview_statement(
    schema: &str,
    table: &str,
    change: &RowChange,
) -> Result<String, String> {
    for cc in &change.column_changes {
        validate_column_identifier(&cc.column)?;
    }
    for pk in &change.pk_conditions {
        validate_column_identifier(&pk.column)?;
    }
    if change.pk_conditions.is_empty() {
        return Err("MySQL row change has no PK conditions".to_string());
    }

    let set_parts: Vec<String> = change
        .column_changes
        .iter()
        .map(|cc| match &cc.value {
            None => format!("`{}` = NULL", cc.column),
            Some(val) => format!("`{}` = '{}'", cc.column, sql_escape_string(val)),
        })
        .collect();

    let where_parts: Vec<String> = change
        .pk_conditions
        .iter()
        .map(|pk| format!("`{}` = '{}'", pk.column, sql_escape_string(&pk.value)))
        .collect();

    Ok(format!(
        "UPDATE `{schema}`.`{table}` SET {} WHERE {};",
        set_parts.join(", "),
        where_parts.join(" AND "),
    ))
}

pub(super) fn build_pg_delete_sql(
    schema: &str,
    table: &str,
    row: &DeleteRowRequest,
    col_cast_map: &HashMap<String, String>,
) -> Result<PgDeleteSql, String> {
    let mut params: Vec<String> = vec![];
    let exec_where = build_pg_exec_where_from_delete(row, col_cast_map, &mut params)
        .map_err(|_| "Row has no PK conditions and no ctid".to_string())?;
    let display_sql = build_pg_delete_preview_statement(schema, table, row, col_cast_map)?;

    Ok(PgDeleteSql {
        exec_sql: format!("DELETE FROM \"{schema}\".\"{table}\" WHERE {exec_where}"),
        display_sql,
        params,
    })
}

pub(super) fn build_pg_delete_preview_statement(
    schema: &str,
    table: &str,
    row: &DeleteRowRequest,
    col_cast_map: &HashMap<String, String>,
) -> Result<String, String> {
    Ok(format!(
        "DELETE FROM \"{schema}\".\"{table}\" WHERE {};",
        build_pg_inline_where_from_delete(row, col_cast_map)?
    ))
}

pub(super) fn build_mysql_delete_sql(
    schema: &str,
    table: &str,
    row: &DeleteRowRequest,
) -> Result<MysqlDeleteSql, String> {
    if row.pk_conditions.is_empty() {
        return Err("MySQL delete requires a primary key".to_string());
    }

    let mut where_parts: Vec<String> = vec![];
    let mut disp_parts: Vec<String> = vec![];
    let mut params: Vec<Value> = vec![];
    for pk in &row.pk_conditions {
        where_parts.push(format!("`{}` = ?", pk.column));
        disp_parts.push(format!(
            "`{}` = '{}'",
            pk.column,
            sql_escape_string(&pk.value)
        ));
        params.push(Value::Bytes(pk.value.as_bytes().to_vec()));
    }

    Ok(MysqlDeleteSql {
        exec_sql: format!(
            "DELETE FROM `{schema}`.`{table}` WHERE {}",
            where_parts.join(" AND ")
        ),
        display_sql: format!(
            "DELETE FROM `{schema}`.`{table}` WHERE {};",
            disp_parts.join(" AND ")
        ),
        params,
    })
}

pub(super) fn build_mysql_delete_preview_sql(
    schema: &str,
    table: &str,
    rows: &[DeleteRowRequest],
) -> String {
    let statements: Vec<String> = rows
        .iter()
        .map(|row| {
            let parts: Vec<String> = row
                .pk_conditions
                .iter()
                .map(|pk| format!("`{}` = '{}'", pk.column, sql_escape_string(&pk.value)))
                .collect();
            format!(
                "DELETE FROM `{schema}`.`{table}` WHERE {};",
                parts.join(" AND ")
            )
        })
        .collect();
    statements.join("\n")
}

fn build_pg_exec_where(
    change: &RowChange,
    col_cast_map: &HashMap<String, String>,
    params: &mut Vec<String>,
) -> Result<String, ()> {
    if !change.pk_conditions.is_empty() {
        build_pg_pk_exec_where(
            change
                .pk_conditions
                .iter()
                .map(|pk| (&pk.column, &pk.value)),
            col_cast_map,
            params,
        )
    } else if let Some(ref ctid) = change.ctid {
        params.push(ctid.clone());
        let p = params.len();
        Ok(format!("ctid = ${}::tid", p))
    } else {
        Err(())
    }
}

fn build_pg_exec_where_from_delete(
    row: &DeleteRowRequest,
    col_cast_map: &HashMap<String, String>,
    params: &mut Vec<String>,
) -> Result<String, ()> {
    if !row.pk_conditions.is_empty() {
        build_pg_pk_exec_where(
            row.pk_conditions.iter().map(|pk| (&pk.column, &pk.value)),
            col_cast_map,
            params,
        )
    } else if let Some(ref ctid) = row.ctid {
        params.push(ctid.clone());
        let p = params.len();
        Ok(format!("ctid = ${}::tid", p))
    } else {
        Err(())
    }
}

fn build_pg_pk_exec_where<'a>(
    pk_conditions: impl Iterator<Item = (&'a String, &'a String)>,
    col_cast_map: &HashMap<String, String>,
    params: &mut Vec<String>,
) -> Result<String, ()> {
    let mut parts = vec![];
    for (column, value) in pk_conditions {
        params.push(value.clone());
        let p = params.len();
        let cast = col_cast_map
            .get(column)
            .map(|s| s.as_str())
            .unwrap_or("text");
        parts.push(format!("\"{}\" = ${}::text::{}", column, p, cast));
    }
    Ok(parts.join(" AND "))
}

fn build_pg_inline_where_from_change(
    change: &RowChange,
    col_cast_map: &HashMap<String, String>,
) -> Result<String, ()> {
    if !change.pk_conditions.is_empty() {
        Ok(build_pg_pk_inline_where(
            change
                .pk_conditions
                .iter()
                .map(|pk| (&pk.column, &pk.value)),
            col_cast_map,
        ))
    } else if let Some(ref ctid) = change.ctid {
        Ok(format!("ctid = '{}'::tid", sql_escape_string(ctid)))
    } else {
        Err(())
    }
}

fn build_pg_inline_where_from_delete(
    row: &DeleteRowRequest,
    col_cast_map: &HashMap<String, String>,
) -> Result<String, String> {
    if !row.pk_conditions.is_empty() {
        Ok(build_pg_pk_inline_where(
            row.pk_conditions.iter().map(|pk| (&pk.column, &pk.value)),
            col_cast_map,
        ))
    } else if let Some(ref ctid) = row.ctid {
        Ok(format!("ctid = '{}'::tid", sql_escape_string(ctid)))
    } else {
        Err("Row has no PK conditions and no ctid".to_string())
    }
}

fn build_pg_pk_inline_where<'a>(
    pk_conditions: impl Iterator<Item = (&'a String, &'a String)>,
    col_cast_map: &HashMap<String, String>,
) -> String {
    let parts: Vec<String> = pk_conditions
        .map(|(column, value)| {
            let cast = col_cast_map
                .get(column)
                .map(|s| s.as_str())
                .unwrap_or("text");
            let escaped = sql_escape_string(value);
            if cast == "text" {
                format!("\"{}\" = '{}'", column, escaped)
            } else {
                format!("\"{}\" = '{}'::{}", column, escaped, cast)
            }
        })
        .collect();
    parts.join(" AND ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commands::data::{ColumnChange, PkCondition};

    fn map(pairs: &[(&str, &str)]) -> HashMap<String, String> {
        pairs
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect()
    }

    #[test]
    fn pg_update_sql_uses_casted_params_in_set_and_pk_where() {
        let change = RowChange {
            pk_conditions: vec![PkCondition {
                column: "id".to_string(),
                value: "8b416fd8-7a0f-4410-a6ed-2fdf8db74d35".to_string(),
            }],
            ctid: None,
            column_changes: vec![ColumnChange {
                column: "name".to_string(),
                value: Some("O'Hara".to_string()),
            }],
        };

        let sql = build_pg_update_sql(
            "public",
            "people",
            &change,
            &map(&[("name", "text"), ("id", "uuid")]),
            &map(&[("name", "text"), ("id", "uuid")]),
        )
        .unwrap();

        assert_eq!(
            sql.sql,
            r#"UPDATE "public"."people" SET "name" = $1::text::text WHERE "id" = $2::text::uuid"#
        );
        assert_eq!(
            sql.params,
            vec![
                "O'Hara".to_string(),
                "8b416fd8-7a0f-4410-a6ed-2fdf8db74d35".to_string()
            ]
        );
    }

    #[test]
    fn pg_delete_by_ctid_uses_tid_in_exec_and_preview() {
        let row = DeleteRowRequest {
            pk_conditions: vec![],
            ctid: Some("(0,42)".to_string()),
        };

        let sql = build_pg_delete_sql("public", "people", &row, &HashMap::new()).unwrap();

        assert_eq!(
            sql.exec_sql,
            r#"DELETE FROM "public"."people" WHERE ctid = $1::tid"#
        );
        assert_eq!(
            sql.display_sql,
            r#"DELETE FROM "public"."people" WHERE ctid = '(0,42)'::tid;"#
        );
        assert_eq!(sql.params, vec!["(0,42)".to_string()]);
    }

    #[test]
    fn mysql_update_preview_escapes_values_and_requires_pk() {
        let change = RowChange {
            pk_conditions: vec![PkCondition {
                column: "id".to_string(),
                value: "7".to_string(),
            }],
            ctid: None,
            column_changes: vec![ColumnChange {
                column: "name".to_string(),
                value: Some("O'Hara".to_string()),
            }],
        };

        let sql = build_mysql_update_preview_sql("app", "people", &[change]).unwrap();

        assert!(sql.contains("UPDATE `app`.`people` SET `name` = 'O''Hara' WHERE `id` = '7';"));

        let missing_pk = RowChange {
            pk_conditions: vec![],
            ctid: None,
            column_changes: vec![ColumnChange {
                column: "name".to_string(),
                value: Some("Ada".to_string()),
            }],
        };
        assert_eq!(
            build_mysql_update_preview_sql("app", "people", &[missing_pk]).unwrap_err(),
            "MySQL row change has no PK conditions"
        );
    }
}
