use std::collections::HashMap;

use mysql_async::Value;

use super::type_mapping::json_to_pg_array_literal;
use super::{validate_column_identifier, DeleteRowRequest, NewRowValues, RowChange};

#[cfg_attr(test, derive(Debug))]
pub(super) struct PgMutationSql {
    pub sql: String,
    pub params: Vec<String>,
}

#[cfg_attr(test, derive(Debug))]
pub(super) struct PgDeleteSql {
    pub exec_sql: String,
    pub display_sql: String,
    pub params: Vec<String>,
}

#[cfg_attr(test, derive(Debug))]
pub(super) struct MysqlMutationSql {
    pub sql: String,
    pub params: Vec<Value>,
}

#[cfg_attr(test, derive(Debug))]
pub(super) struct MysqlDeleteSql {
    pub exec_sql: String,
    pub display_sql: String,
    pub params: Vec<Value>,
}

pub(super) fn sql_escape_string(s: &str) -> String {
    s.replace('\'', "''")
}

pub(super) fn build_pg_update_sql(
    schema: &str,
    table: &str,
    change: &RowChange,
    col_type_map: &HashMap<String, String>,
    col_cast_map: &HashMap<String, String>,
) -> Result<PgMutationSql, String> {
    for cc in &change.column_changes {
        validate_column_identifier(&cc.column)?;
    }
    for pk in &change.pk_conditions {
        validate_column_identifier(&pk.column)?;
    }

    let mut params: Vec<String> = vec![];
    let mut set_parts: Vec<String> = vec![];

    for cc in &change.column_changes {
        if let Some(ref val) = cc.value {
            let udt = col_type_map
                .get(&cc.column)
                .map(|s| s.as_str())
                .unwrap_or("text");
            if udt.starts_with('_') {
                let elem_type = udt.trim_start_matches('_');
                params.push(json_to_pg_array_literal(val)?);
                let p = params.len();
                set_parts.push(format!("\"{}\" = ${}::text::{}[]", cc.column, p, elem_type));
            } else {
                params.push(val.clone());
                let p = params.len();
                let cast = col_cast_map
                    .get(&cc.column)
                    .map(|s| s.as_str())
                    .unwrap_or("text");
                set_parts.push(format!("\"{}\" = ${}::text::{}", cc.column, p, cast));
            }
        } else {
            set_parts.push(format!("\"{}\" = NULL", cc.column));
        }
    }

    let where_clause = build_pg_exec_where(change, col_cast_map, &mut params)
        .map_err(|_| "Row change has no PK conditions and no ctid".to_string())?;

    Ok(PgMutationSql {
        sql: format!(
            "UPDATE \"{schema}\".\"{table}\" SET {} WHERE {where_clause}",
            set_parts.join(", ")
        ),
        params,
    })
}

pub(super) fn build_pg_update_preview_sql(
    schema: &str,
    table: &str,
    changes: &[RowChange],
    col_type_map: &HashMap<String, String>,
    col_cast_map: &HashMap<String, String>,
) -> Result<String, String> {
    let mut statements: Vec<String> = vec![];

    for change in changes {
        if change.column_changes.is_empty() {
            continue;
        }
        statements.push(build_pg_update_preview_statement(
            schema,
            table,
            change,
            col_type_map,
            col_cast_map,
        )?);
    }

    if statements.is_empty() {
        return Ok(String::new());
    }

    Ok(format!(
        "BEGIN;\n-- Generated by Esploro from inline edits. Review before running.\n{}\nCOMMIT;",
        statements.join("\n"),
    ))
}

fn build_pg_update_preview_statement(
    schema: &str,
    table: &str,
    change: &RowChange,
    col_type_map: &HashMap<String, String>,
    col_cast_map: &HashMap<String, String>,
) -> Result<String, String> {
    for cc in &change.column_changes {
        validate_column_identifier(&cc.column)?;
    }
    for pk in &change.pk_conditions {
        validate_column_identifier(&pk.column)?;
    }

    let mut set_parts: Vec<String> = vec![];
    for cc in &change.column_changes {
        let part = match &cc.value {
            None => format!("\"{}\" = NULL", cc.column),
            Some(val) => {
                let udt = col_type_map
                    .get(&cc.column)
                    .map(|s| s.as_str())
                    .unwrap_or("text");
                if udt.starts_with('_') {
                    let elem_type = udt.trim_start_matches('_');
                    let pg_array = json_to_pg_array_literal(val)?;
                    format!(
                        "\"{}\" = '{}'::{}[]",
                        cc.column,
                        sql_escape_string(&pg_array),
                        elem_type
                    )
                } else {
                    let cast = col_cast_map
                        .get(&cc.column)
                        .map(|s| s.as_str())
                        .unwrap_or("text");
                    let escaped = sql_escape_string(val);
                    if cast == "text" {
                        format!("\"{}\" = '{}'", cc.column, escaped)
                    } else {
                        format!("\"{}\" = '{}'::{}", cc.column, escaped, cast)
                    }
                }
            }
        };
        set_parts.push(part);
    }

    let where_clause = build_pg_inline_where_from_change(change, col_cast_map)
        .map_err(|_| "Row change has no PK conditions and no ctid".to_string())?;

    Ok(format!(
        "UPDATE \"{schema}\".\"{table}\" SET {} WHERE {where_clause};",
        set_parts.join(", ")
    ))
}

pub(super) fn build_mysql_update_sql(
    schema: &str,
    table: &str,
    change: &RowChange,
) -> Result<MysqlMutationSql, String> {
    for cc in &change.column_changes {
        validate_column_identifier(&cc.column)?;
    }
    for pk in &change.pk_conditions {
        validate_column_identifier(&pk.column)?;
    }
    if change.pk_conditions.is_empty() {
        return Err("MySQL row change has no PK conditions".to_string());
    }

    let mut set_params: Vec<Value> = vec![];
    let mut set_parts: Vec<String> = vec![];

    for cc in &change.column_changes {
        if let Some(ref val) = cc.value {
            set_parts.push(format!("`{}` = ?", cc.column));
            set_params.push(Value::Bytes(val.as_bytes().to_vec()));
        } else {
            set_parts.push(format!("`{}` = NULL", cc.column));
        }
    }

    let mut where_parts: Vec<String> = vec![];
    let mut where_params: Vec<Value> = vec![];
    for pk in &change.pk_conditions {
        where_parts.push(format!("`{}` = ?", pk.column));
        where_params.push(Value::Bytes(pk.value.as_bytes().to_vec()));
    }

    Ok(MysqlMutationSql {
        sql: format!(
            "UPDATE `{schema}`.`{table}` SET {} WHERE {}",
            set_parts.join(", "),
            where_parts.join(" AND "),
        ),
        params: set_params.into_iter().chain(where_params).collect(),
    })
}

pub(super) fn build_mysql_update_preview_sql(
    schema: &str,
    table: &str,
    changes: &[RowChange],
) -> Result<String, String> {
    let mut statements: Vec<String> = vec![];

    for change in changes {
        if change.column_changes.is_empty() {
            continue;
        }
        statements.push(build_mysql_update_preview_statement(schema, table, change)?);
    }

    if statements.is_empty() {
        return Ok(String::new());
    }

    Ok(format!(
        "START TRANSACTION;\n-- Generated by Esploro from inline edits. Review before running.\n{}\nCOMMIT;",
        statements.join("\n"),
    ))
}

fn build_mysql_update_preview_statement(
    schema: &str,
    table: &str,
    change: &RowChange,
) -> Result<String, String> {
    for cc in &change.column_changes {
        validate_column_identifier(&cc.column)?;
    }
    for pk in &change.pk_conditions {
        validate_column_identifier(&pk.column)?;
    }
    if change.pk_conditions.is_empty() {
        return Err("MySQL row change has no PK conditions".to_string());
    }

    let set_parts: Vec<String> = change
        .column_changes
        .iter()
        .map(|cc| match &cc.value {
            None => format!("`{}` = NULL", cc.column),
            Some(val) => format!("`{}` = '{}'", cc.column, sql_escape_string(val)),
        })
        .collect();

    let where_parts: Vec<String> = change
        .pk_conditions
        .iter()
        .map(|pk| format!("`{}` = '{}'", pk.column, sql_escape_string(&pk.value)))
        .collect();

    Ok(format!(
        "UPDATE `{schema}`.`{table}` SET {} WHERE {};",
        set_parts.join(", "),
        where_parts.join(" AND "),
    ))
}

pub(super) fn build_pg_insert_sql(
    schema: &str,
    table: &str,
    row: &NewRowValues,
    col_type_map: &HashMap<String, String>,
    col_cast_map: &HashMap<String, String>,
) -> Result<PgMutationSql, String> {
    for cc in &row.column_values {
        validate_column_identifier(&cc.column)?;
    }

    if row.column_values.is_empty() {
        return Ok(PgMutationSql {
            sql: format!("INSERT INTO \"{schema}\".\"{table}\" DEFAULT VALUES"),
            params: vec![],
        });
    }

    let mut params: Vec<String> = vec![];
    let mut columns: Vec<String> = vec![];
    let mut value_parts: Vec<String> = vec![];

    for cc in &row.column_values {
        columns.push(format!("\"{}\"", cc.column));
        if let Some(ref val) = cc.value {
            let udt = col_type_map
                .get(&cc.column)
                .map(|s| s.as_str())
                .unwrap_or("text");
            if udt.starts_with('_') {
                let elem_type = udt.trim_start_matches('_');
                params.push(json_to_pg_array_literal(val)?);
                let p = params.len();
                value_parts.push(format!("${}::text::{}[]", p, elem_type));
            } else {
                params.push(val.clone());
                let p = params.len();
                let cast = col_cast_map
                    .get(&cc.column)
                    .map(|s| s.as_str())
                    .unwrap_or("text");
                value_parts.push(format!("${}::text::{}", p, cast));
            }
        } else {
            value_parts.push("NULL".to_string());
        }
    }

    Ok(PgMutationSql {
        sql: format!(
            "INSERT INTO \"{schema}\".\"{table}\" ({}) VALUES ({})",
            columns.join(", "),
            value_parts.join(", ")
        ),
        params,
    })
}

pub(super) fn build_mysql_insert_sql(
    schema: &str,
    table: &str,
    row: &NewRowValues,
) -> Result<MysqlMutationSql, String> {
    for cc in &row.column_values {
        validate_column_identifier(&cc.column)?;
    }

    if row.column_values.is_empty() {
        return Ok(MysqlMutationSql {
            sql: format!("INSERT INTO `{schema}`.`{table}` VALUES ()"),
            params: vec![],
        });
    }

    let mut params: Vec<Value> = vec![];
    let mut columns: Vec<String> = vec![];
    let mut value_parts: Vec<String> = vec![];

    for cc in &row.column_values {
        columns.push(format!("`{}`", cc.column));
        if let Some(ref val) = cc.value {
            value_parts.push("?".to_string());
            params.push(Value::Bytes(val.as_bytes().to_vec()));
        } else {
            value_parts.push("NULL".to_string());
        }
    }

    Ok(MysqlMutationSql {
        sql: format!(
            "INSERT INTO `{schema}`.`{table}` ({}) VALUES ({})",
            columns.join(", "),
            value_parts.join(", ")
        ),
        params,
    })
}

pub(super) fn build_pg_delete_sql(
    schema: &str,
    table: &str,
    row: &DeleteRowRequest,
    col_cast_map: &HashMap<String, String>,
) -> Result<PgDeleteSql, String> {
    let mut params: Vec<String> = vec![];
    let exec_where = build_pg_exec_where_from_delete(row, col_cast_map, &mut params)
        .map_err(|_| "Row has no PK conditions and no ctid".to_string())?;
    let display_sql = build_pg_delete_preview_statement(schema, table, row, col_cast_map)?;

    Ok(PgDeleteSql {
        exec_sql: format!("DELETE FROM \"{schema}\".\"{table}\" WHERE {exec_where}"),
        display_sql,
        params,
    })
}

pub(super) fn build_pg_delete_preview_statement(
    schema: &str,
    table: &str,
    row: &DeleteRowRequest,
    col_cast_map: &HashMap<String, String>,
) -> Result<String, String> {
    Ok(format!(
        "DELETE FROM \"{schema}\".\"{table}\" WHERE {};",
        build_pg_inline_where_from_delete(row, col_cast_map)?
    ))
}

pub(super) fn build_mysql_delete_sql(
    schema: &str,
    table: &str,
    row: &DeleteRowRequest,
) -> Result<MysqlDeleteSql, String> {
    if row.pk_conditions.is_empty() {
        return Err("MySQL delete requires a primary key".to_string());
    }

    let mut where_parts: Vec<String> = vec![];
    let mut disp_parts: Vec<String> = vec![];
    let mut params: Vec<Value> = vec![];
    for pk in &row.pk_conditions {
        where_parts.push(format!("`{}` = ?", pk.column));
        disp_parts.push(format!(
            "`{}` = '{}'",
            pk.column,
            sql_escape_string(&pk.value)
        ));
        params.push(Value::Bytes(pk.value.as_bytes().to_vec()));
    }

    Ok(MysqlDeleteSql {
        exec_sql: format!(
            "DELETE FROM `{schema}`.`{table}` WHERE {}",
            where_parts.join(" AND ")
        ),
        display_sql: format!(
            "DELETE FROM `{schema}`.`{table}` WHERE {};",
            disp_parts.join(" AND ")
        ),
        params,
    })
}

pub(super) fn build_mysql_delete_preview_sql(
    schema: &str,
    table: &str,
    rows: &[DeleteRowRequest],
) -> String {
    let statements: Vec<String> = rows
        .iter()
        .map(|row| {
            let parts: Vec<String> = row
                .pk_conditions
                .iter()
                .map(|pk| format!("`{}` = '{}'", pk.column, sql_escape_string(&pk.value)))
                .collect();
            format!(
                "DELETE FROM `{schema}`.`{table}` WHERE {};",
                parts.join(" AND ")
            )
        })
        .collect();
    statements.join("\n")
}

fn build_pg_exec_where(
    change: &RowChange,
    col_cast_map: &HashMap<String, String>,
    params: &mut Vec<String>,
) -> Result<String, ()> {
    if !change.pk_conditions.is_empty() {
        build_pg_pk_exec_where(
            change
                .pk_conditions
                .iter()
                .map(|pk| (&pk.column, &pk.value)),
            col_cast_map,
            params,
        )
    } else if let Some(ref ctid) = change.ctid {
        params.push(ctid.clone());
        let p = params.len();
        Ok(format!("ctid = ${}::tid", p))
    } else {
        Err(())
    }
}

fn build_pg_exec_where_from_delete(
    row: &DeleteRowRequest,
    col_cast_map: &HashMap<String, String>,
    params: &mut Vec<String>,
) -> Result<String, ()> {
    if !row.pk_conditions.is_empty() {
        build_pg_pk_exec_where(
            row.pk_conditions.iter().map(|pk| (&pk.column, &pk.value)),
            col_cast_map,
            params,
        )
    } else if let Some(ref ctid) = row.ctid {
        params.push(ctid.clone());
        let p = params.len();
        Ok(format!("ctid = ${}::tid", p))
    } else {
        Err(())
    }
}

fn build_pg_pk_exec_where<'a>(
    pk_conditions: impl Iterator<Item = (&'a String, &'a String)>,
    col_cast_map: &HashMap<String, String>,
    params: &mut Vec<String>,
) -> Result<String, ()> {
    let mut parts = vec![];
    for (column, value) in pk_conditions {
        params.push(value.clone());
        let p = params.len();
        let cast = col_cast_map
            .get(column)
            .map(|s| s.as_str())
            .unwrap_or("text");
        parts.push(format!("\"{}\" = ${}::text::{}", column, p, cast));
    }
    Ok(parts.join(" AND "))
}

fn build_pg_inline_where_from_change(
    change: &RowChange,
    col_cast_map: &HashMap<String, String>,
) -> Result<String, ()> {
    if !change.pk_conditions.is_empty() {
        Ok(build_pg_pk_inline_where(
            change
                .pk_conditions
                .iter()
                .map(|pk| (&pk.column, &pk.value)),
            col_cast_map,
        ))
    } else if let Some(ref ctid) = change.ctid {
        Ok(format!("ctid = '{}'::tid", sql_escape_string(ctid)))
    } else {
        Err(())
    }
}

fn build_pg_inline_where_from_delete(
    row: &DeleteRowRequest,
    col_cast_map: &HashMap<String, String>,
) -> Result<String, String> {
    if !row.pk_conditions.is_empty() {
        Ok(build_pg_pk_inline_where(
            row.pk_conditions.iter().map(|pk| (&pk.column, &pk.value)),
            col_cast_map,
        ))
    } else if let Some(ref ctid) = row.ctid {
        Ok(format!("ctid = '{}'::tid", sql_escape_string(ctid)))
    } else {
        Err("Row has no PK conditions and no ctid".to_string())
    }
}

fn build_pg_pk_inline_where<'a>(
    pk_conditions: impl Iterator<Item = (&'a String, &'a String)>,
    col_cast_map: &HashMap<String, String>,
) -> String {
    let parts: Vec<String> = pk_conditions
        .map(|(column, value)| {
            let cast = col_cast_map
                .get(column)
                .map(|s| s.as_str())
                .unwrap_or("text");
            let escaped = sql_escape_string(value);
            if cast == "text" {
                format!("\"{}\" = '{}'", column, escaped)
            } else {
                format!("\"{}\" = '{}'::{}", column, escaped, cast)
            }
        })
        .collect();
    parts.join(" AND ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commands::data::{ColumnChange, NewRowValues, PkCondition};

    fn map(pairs: &[(&str, &str)]) -> HashMap<String, String> {
        pairs
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect()
    }

    #[test]
    fn pg_update_sql_uses_casted_params_in_set_and_pk_where() {
        let change = RowChange {
            pk_conditions: vec![PkCondition {
                column: "id".to_string(),
                value: "8b416fd8-7a0f-4410-a6ed-2fdf8db74d35".to_string(),
            }],
            ctid: None,
            column_changes: vec![ColumnChange {
                column: "name".to_string(),
                value: Some("O'Hara".to_string()),
            }],
        };

        let sql = build_pg_update_sql(
            "public",
            "people",
            &change,
            &map(&[("name", "text"), ("id", "uuid")]),
            &map(&[("name", "text"), ("id", "uuid")]),
        )
        .unwrap();

        assert_eq!(
            sql.sql,
            r#"UPDATE "public"."people" SET "name" = $1::text::text WHERE "id" = $2::text::uuid"#
        );
        assert_eq!(
            sql.params,
            vec![
                "O'Hara".to_string(),
                "8b416fd8-7a0f-4410-a6ed-2fdf8db74d35".to_string()
            ]
        );
    }

    #[test]
    fn pg_delete_by_ctid_uses_tid_in_exec_and_preview() {
        let row = DeleteRowRequest {
            pk_conditions: vec![],
            ctid: Some("(0,42)".to_string()),
        };

        let sql = build_pg_delete_sql("public", "people", &row, &HashMap::new()).unwrap();

        assert_eq!(
            sql.exec_sql,
            r#"DELETE FROM "public"."people" WHERE ctid = $1::tid"#
        );
        assert_eq!(
            sql.display_sql,
            r#"DELETE FROM "public"."people" WHERE ctid = '(0,42)'::tid;"#
        );
        assert_eq!(sql.params, vec!["(0,42)".to_string()]);
    }

    #[test]
    fn mysql_update_preview_escapes_values_and_requires_pk() {
        let change = RowChange {
            pk_conditions: vec![PkCondition {
                column: "id".to_string(),
                value: "7".to_string(),
            }],
            ctid: None,
            column_changes: vec![ColumnChange {
                column: "name".to_string(),
                value: Some("O'Hara".to_string()),
            }],
        };

        let sql = build_mysql_update_preview_sql("app", "people", &[change]).unwrap();

        assert!(sql.contains("UPDATE `app`.`people` SET `name` = 'O''Hara' WHERE `id` = '7';"));

        let missing_pk = RowChange {
            pk_conditions: vec![],
            ctid: None,
            column_changes: vec![ColumnChange {
                column: "name".to_string(),
                value: Some("Ada".to_string()),
            }],
        };
        assert_eq!(
            build_mysql_update_preview_sql("app", "people", &[missing_pk]).unwrap_err(),
            "MySQL row change has no PK conditions"
        );
    }

    fn bytes(s: &str) -> Value {
        Value::Bytes(s.as_bytes().to_vec())
    }

    fn pk(column: &str, value: &str) -> PkCondition {
        PkCondition {
            column: column.to_string(),
            value: value.to_string(),
        }
    }

    fn set(column: &str, value: Option<&str>) -> ColumnChange {
        ColumnChange {
            column: column.to_string(),
            value: value.map(str::to_string),
        }
    }

    fn change(pks: Vec<PkCondition>, ctid: Option<&str>, sets: Vec<ColumnChange>) -> RowChange {
        RowChange {
            pk_conditions: pks,
            ctid: ctid.map(str::to_string),
            column_changes: sets,
        }
    }

    fn delete_row(pks: Vec<PkCondition>, ctid: Option<&str>) -> DeleteRowRequest {
        DeleteRowRequest {
            pk_conditions: pks,
            ctid: ctid.map(str::to_string),
        }
    }

    #[test]
    fn mysql_update_sql_binds_set_values_before_pk_values() {
        let change = change(
            vec![pk("id", "7")],
            None,
            vec![set("name", Some("O'Hara")), set("nickname", None)],
        );

        let sql = build_mysql_update_sql("app", "people", &change).unwrap();

        assert_eq!(
            sql.sql,
            "UPDATE `app`.`people` SET `name` = ?, `nickname` = NULL WHERE `id` = ?"
        );
        assert_eq!(sql.params, vec![bytes("O'Hara"), bytes("7")]);
    }

    #[test]
    fn update_sql_placeholders_differ_per_driver_for_the_same_change() {
        let change = change(vec![pk("id", "7")], None, vec![set("name", Some("Ada"))]);
        let casts = map(&[("name", "text"), ("id", "bigint")]);

        let pg = build_pg_update_sql("public", "people", &change, &casts, &casts).unwrap();
        let mysql = build_mysql_update_sql("app", "people", &change).unwrap();

        assert_eq!(
            pg.sql,
            r#"UPDATE "public"."people" SET "name" = $1::text::text WHERE "id" = $2::text::bigint"#
        );
        assert_eq!(
            mysql.sql,
            "UPDATE `app`.`people` SET `name` = ? WHERE `id` = ?"
        );
    }

    #[test]
    fn pg_update_sql_falls_back_to_ctid_when_there_is_no_pk() {
        let change = change(vec![], Some("(0,42)"), vec![set("name", Some("Ada"))]);

        let sql = build_pg_update_sql(
            "public",
            "people",
            &change,
            &HashMap::new(),
            &HashMap::new(),
        )
        .unwrap();

        assert_eq!(
            sql.sql,
            r#"UPDATE "public"."people" SET "name" = $1::text::text WHERE ctid = $2::tid"#
        );
        assert_eq!(sql.params, vec!["Ada".to_string(), "(0,42)".to_string()]);
    }

    #[test]
    fn mysql_update_sql_has_no_ctid_fallback() {
        let change = change(vec![], Some("(0,42)"), vec![set("name", Some("Ada"))]);

        assert_eq!(
            build_mysql_update_sql("app", "people", &change).unwrap_err(),
            "MySQL row change has no PK conditions"
        );
    }

    #[test]
    fn pg_update_sql_errors_without_pk_or_ctid() {
        let change = change(vec![], None, vec![set("name", Some("Ada"))]);

        assert_eq!(
            build_pg_update_sql(
                "public",
                "people",
                &change,
                &HashMap::new(),
                &HashMap::new()
            )
            .unwrap_err(),
            "Row change has no PK conditions and no ctid"
        );
    }

    #[test]
    fn pg_update_sql_expands_array_columns_to_array_literals() {
        let change = change(vec![pk("id", "7")], None, vec![set("tags", Some("[1, 2]"))]);

        let sql = build_pg_update_sql(
            "public",
            "people",
            &change,
            &map(&[("tags", "_int4")]),
            &map(&[("id", "bigint")]),
        )
        .unwrap();

        assert_eq!(
            sql.sql,
            r#"UPDATE "public"."people" SET "tags" = $1::text::int4[] WHERE "id" = $2::text::bigint"#
        );
        assert_eq!(
            sql.params,
            vec![r#"{"1","2"}"#.to_string(), "7".to_string()]
        );
    }

    #[test]
    fn update_sql_rejects_unsafe_identifiers_on_both_drivers() {
        let pg_change = change(vec![pk("id", "7")], None, vec![set(r#"name" = 'x"#, None)]);
        let mysql_change = change(vec![pk("id", "7")], None, vec![set("name` = 'x", None)]);

        assert!(build_pg_update_sql(
            "public",
            "people",
            &pg_change,
            &HashMap::new(),
            &HashMap::new()
        )
        .unwrap_err()
        .contains("Invalid identifier"));
        assert!(build_mysql_update_sql("app", "people", &mysql_change)
            .unwrap_err()
            .contains("Invalid identifier"));
    }

    #[test]
    fn pg_update_preview_wraps_statements_in_a_begin_commit_block() {
        let changes = vec![change(
            vec![pk("id", "7")],
            None,
            vec![set("name", Some("O'Hara")), set("nickname", None)],
        )];

        let sql = build_pg_update_preview_sql(
            "public",
            "people",
            &changes,
            &map(&[("name", "text")]),
            &map(&[("name", "text"), ("id", "bigint")]),
        )
        .unwrap();

        assert_eq!(
            sql,
            "BEGIN;\n\
             -- Generated by Esploro from inline edits. Review before running.\n\
             UPDATE \"public\".\"people\" SET \"name\" = 'O''Hara', \"nickname\" = NULL WHERE \"id\" = '7'::bigint;\n\
             COMMIT;"
        );
    }

    #[test]
    fn mysql_update_preview_wraps_statements_in_a_start_transaction_block() {
        let changes = vec![change(
            vec![pk("id", "7")],
            None,
            vec![set("name", Some("O'Hara")), set("nickname", None)],
        )];

        let sql = build_mysql_update_preview_sql("app", "people", &changes).unwrap();

        assert_eq!(
            sql,
            "START TRANSACTION;\n\
             -- Generated by Esploro from inline edits. Review before running.\n\
             UPDATE `app`.`people` SET `name` = 'O''Hara', `nickname` = NULL WHERE `id` = '7';\n\
             COMMIT;"
        );
    }

    #[test]
    fn update_preview_is_empty_when_no_change_touches_a_column_on_either_driver() {
        let changes = vec![change(vec![pk("id", "7")], None, vec![])];

        assert_eq!(
            build_pg_update_preview_sql(
                "public",
                "people",
                &changes,
                &HashMap::new(),
                &HashMap::new()
            )
            .unwrap(),
            ""
        );
        assert_eq!(
            build_mysql_update_preview_sql("app", "people", &changes).unwrap(),
            ""
        );
    }

    #[test]
    fn pg_update_preview_inlines_text_values_without_a_cast() {
        let changes = vec![change(
            vec![pk("id", "abc")],
            None,
            vec![set("name", Some("Ada"))],
        )];

        let sql = build_pg_update_preview_sql(
            "public",
            "people",
            &changes,
            &map(&[("name", "text")]),
            &map(&[("name", "text"), ("id", "text")]),
        )
        .unwrap();

        assert!(sql.contains(r#"SET "name" = 'Ada' WHERE "id" = 'abc';"#));
    }

    #[test]
    fn pg_update_preview_falls_back_to_an_inline_ctid() {
        let changes = vec![change(vec![], Some("(0,42)"), vec![set("name", None)])];

        let sql = build_pg_update_preview_sql(
            "public",
            "people",
            &changes,
            &HashMap::new(),
            &HashMap::new(),
        )
        .unwrap();

        assert!(sql.contains(r#"SET "name" = NULL WHERE ctid = '(0,42)'::tid;"#));
    }

    #[test]
    fn pg_update_preview_inlines_array_literals() {
        let changes = vec![change(
            vec![pk("id", "7")],
            None,
            vec![set("tags", Some(r#"["a'b"]"#))],
        )];

        let sql = build_pg_update_preview_sql(
            "public",
            "people",
            &changes,
            &map(&[("tags", "_text")]),
            &map(&[("id", "bigint")]),
        )
        .unwrap();

        assert!(sql.contains(r#"SET "tags" = '{"a''b"}'::text[]"#));
    }

    #[test]
    fn pg_delete_sql_uses_casted_params_and_inlined_preview_for_pks() {
        let row = delete_row(vec![pk("id", "7"), pk("tenant", "acme")], None);

        let sql = build_pg_delete_sql("public", "people", &row, &map(&[("id", "bigint")])).unwrap();

        assert_eq!(
            sql.exec_sql,
            r#"DELETE FROM "public"."people" WHERE "id" = $1::text::bigint AND "tenant" = $2::text::text"#
        );
        assert_eq!(
            sql.display_sql,
            r#"DELETE FROM "public"."people" WHERE "id" = '7'::bigint AND "tenant" = 'acme';"#
        );
        assert_eq!(sql.params, vec!["7".to_string(), "acme".to_string()]);
    }

    #[test]
    fn mysql_delete_sql_uses_positional_params_and_inlined_preview_for_pks() {
        let row = delete_row(vec![pk("id", "7"), pk("tenant", "O'Hara")], None);

        let sql = build_mysql_delete_sql("app", "people", &row).unwrap();

        assert_eq!(
            sql.exec_sql,
            "DELETE FROM `app`.`people` WHERE `id` = ? AND `tenant` = ?"
        );
        assert_eq!(
            sql.display_sql,
            "DELETE FROM `app`.`people` WHERE `id` = '7' AND `tenant` = 'O''Hara';"
        );
        assert_eq!(sql.params, vec![bytes("7"), bytes("O'Hara")]);
    }

    #[test]
    fn mysql_delete_sql_requires_a_primary_key() {
        let row = delete_row(vec![], Some("(0,42)"));

        assert_eq!(
            build_mysql_delete_sql("app", "people", &row).unwrap_err(),
            "MySQL delete requires a primary key"
        );
    }

    #[test]
    fn pg_delete_sql_errors_without_pk_or_ctid() {
        let row = delete_row(vec![], None);

        assert_eq!(
            build_pg_delete_sql("public", "people", &row, &HashMap::new()).unwrap_err(),
            "Row has no PK conditions and no ctid"
        );
    }

    #[test]
    fn pg_delete_preview_statement_inlines_pk_values() {
        let row = delete_row(vec![pk("id", "O'Hara")], None);

        let sql =
            build_pg_delete_preview_statement("public", "people", &row, &HashMap::new()).unwrap();

        assert_eq!(
            sql,
            r#"DELETE FROM "public"."people" WHERE "id" = 'O''Hara';"#
        );
    }

    #[test]
    fn mysql_delete_preview_joins_one_statement_per_row() {
        let rows = vec![
            delete_row(vec![pk("id", "7")], None),
            delete_row(vec![pk("id", "8")], None),
        ];

        let sql = build_mysql_delete_preview_sql("app", "people", &rows);

        assert_eq!(
            sql,
            "DELETE FROM `app`.`people` WHERE `id` = '7';\n\
             DELETE FROM `app`.`people` WHERE `id` = '8';"
        );
    }

    #[test]
    fn delete_preview_quoting_differs_per_driver_for_the_same_row() {
        let row = delete_row(vec![pk("id", "7")], None);

        assert_eq!(
            build_pg_delete_preview_statement("public", "people", &row, &HashMap::new()).unwrap(),
            r#"DELETE FROM "public"."people" WHERE "id" = '7';"#
        );
        assert_eq!(
            build_mysql_delete_preview_sql("app", "people", std::slice::from_ref(&row)),
            "DELETE FROM `app`.`people` WHERE `id` = '7';"
        );
    }

    fn new_row(sets: Vec<ColumnChange>) -> NewRowValues {
        NewRowValues {
            column_values: sets,
        }
    }

    #[test]
    fn pg_insert_sql_uses_casted_params_for_each_column() {
        let row = new_row(vec![
            set("name", Some("O'Hara")),
            set("age", Some("42")),
            set("nickname", None),
        ]);

        let sql = build_pg_insert_sql(
            "public",
            "people",
            &row,
            &map(&[("name", "text"), ("age", "int4")]),
            &map(&[("name", "text"), ("age", "int4")]),
        )
        .unwrap();

        assert_eq!(
            sql.sql,
            r#"INSERT INTO "public"."people" ("name", "age", "nickname") VALUES ($1::text::text, $2::text::int4, NULL)"#
        );
        assert_eq!(
            sql.params,
            vec!["O'Hara".to_string(), "42".to_string()]
        );
    }

    #[test]
    fn pg_insert_sql_expands_array_columns_to_array_literals() {
        let row = new_row(vec![set("tags", Some("[1, 2]"))]);

        let sql = build_pg_insert_sql(
            "public",
            "people",
            &row,
            &map(&[("tags", "_int4")]),
            &HashMap::new(),
        )
        .unwrap();

        assert_eq!(
            sql.sql,
            r#"INSERT INTO "public"."people" ("tags") VALUES ($1::text::int4[])"#
        );
        assert_eq!(sql.params, vec![r#"{"1","2"}"#.to_string()]);
    }

    #[test]
    fn pg_insert_sql_uses_default_values_when_no_columns_are_set() {
        let row = new_row(vec![]);

        let sql = build_pg_insert_sql("public", "people", &row, &HashMap::new(), &HashMap::new())
            .unwrap();

        assert_eq!(
            sql.sql,
            r#"INSERT INTO "public"."people" DEFAULT VALUES"#
        );
        assert!(sql.params.is_empty());
    }

    #[test]
    fn pg_insert_sql_rejects_unsafe_identifiers() {
        let row = new_row(vec![set(r#"name" = 'x"#, None)]);

        assert!(
            build_pg_insert_sql("public", "people", &row, &HashMap::new(), &HashMap::new())
                .unwrap_err()
                .contains("Invalid identifier")
        );
    }

    #[test]
    fn mysql_insert_sql_binds_placeholders_for_each_column() {
        let row = new_row(vec![set("name", Some("O'Hara")), set("nickname", None)]);

        let sql = build_mysql_insert_sql("app", "people", &row).unwrap();

        assert_eq!(
            sql.sql,
            "INSERT INTO `app`.`people` (`name`, `nickname`) VALUES (?, NULL)"
        );
        assert_eq!(sql.params, vec![bytes("O'Hara")]);
    }

    #[test]
    fn mysql_insert_sql_uses_empty_values_when_no_columns_are_set() {
        let row = new_row(vec![]);

        let sql = build_mysql_insert_sql("app", "people", &row).unwrap();

        assert_eq!(sql.sql, "INSERT INTO `app`.`people` VALUES ()");
        assert!(sql.params.is_empty());
    }

    #[test]
    fn mysql_insert_sql_rejects_unsafe_identifiers() {
        let row = new_row(vec![set("name` = 'x", None)]);

        assert!(build_mysql_insert_sql("app", "people", &row)
            .unwrap_err()
            .contains("Invalid identifier"));
    }

    #[test]
    fn sql_escape_string_doubles_single_quotes_for_both_drivers() {
        assert_eq!(sql_escape_string("O'Hara"), "O''Hara");
        assert_eq!(sql_escape_string("plain"), "plain");
    }
}
